name: CI (main)

on:
  push:
    branches:
      - '**'

jobs:
  unit:
    name: Unit Testing
    timeout-minutes: 10
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.7.6]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements-ci.txt ]; then pip install -r requirements-ci.txt; fi
      - name: Test with pytest
        run: |
          python -m unittest CUR_GRID_FDM/tests/test_Mesh.py
